# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 250617bdb182dd01570a4d240c09655ee7e9710f63f42f91942866fb699c0294a005b68d4d6208040fefc9f1468a6648d165f0f43292c7593c1db70c1f561d5f

test:
  secret_key_base: f9e1e09c9ab7a825f994125c45e700709444c0338ae2556c726df4db9f386f056331eab853de73a8ec1449b91f94b42e7c4b3c5fb8d047c10130a6248d1b4877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
